/** Kiểm tra state, cursor và status điều phối. */
const { section, check } = require("../../lib/assert");
const { taoHopCat, napServer } = require("../../lib/load-gas");

async function chay(so) {
  section("FBM sync — orchestration");
  const props = { data: {} };
  let propertyWrites = 0;
  const propertyApi = { getProperty: (key) => props.data[key] || null, setProperty: (key, value) => { propertyWrites += 1; props.data[key] = String(value); } };
  const orchestration = taoHopCat({
    FbmSync: {},
    PropertiesService: { getDocumentProperties: () => propertyApi, getScriptProperties: () => propertyApi }
  });
  napServer(orchestration, 'fbm_sync/schema/FbmFields.js', 'fbm_sync/protocol/Protocol.js', 'fbm_sync/state/State.js', 'fbm_sync/diagnostic/Trace.js', 'fbm_sync/state/Scheduler.js', 'fbm_sync/report/Report.js', 'fbm_sync/read/GridRead.js', 'fbm_sync/write/RequestBuilders.js', 'fbm_sync/transport/TransportCore.js', 'fbm_sync/transport/PushFlow.js', 'fbm_sync/transport/PullFlow.js', 'fbm_sync/transport/EntryPoints.js');
  const started = orchestration.FbmSync.start({ mode: 'read' });
  check(so, 'start bat dau bang bootstrap Customer', started.request.meta.kind, 'authorize');
  const conflictCarry = orchestration.FbmSync.stateRead();
  conflictCarry.metadata.conflicts = [{ entity: 'activity', id: 'ACT-KEEP' }];
  conflictCarry.locks = { 'activity:ACT-KEEP': { owner: 'sync', reason: 'conflict' } };
  orchestration.FbmSync.stateWrite(conflictCarry);
  conflictCarry.phase = 'conflict';
  orchestration.FbmSync.stateWrite(conflictCarry);
  const carriedStart = orchestration.FbmSync.stateStart('', 'checking_session', 0, { preserveConflicts: true });
  check(so, 'phien moi giu conflict chua giai quyet va khoa sync', [carriedStart.metadata.conflicts.length, carriedStart.counts.conflict, carriedStart.locks['activity:ACT-KEEP'].reason], [1, 1, 'conflict']);
  orchestration.FbmSync.readLocal = () => [];
  const orphanState = orchestration.FbmSync.stateRead();
  orphanState.phase = 'conflict';
  orphanState.metadata.conflicts = [{ entity: 'activity', id: 'ACT-DELETED' }];
  orphanState.counts.conflict = 1;
  orphanState.locks = { 'activity:ACT-DELETED': { owner: 'sync', reason: 'conflict' } };
  orchestration.FbmSync.stateWrite(orphanState);
  const cleanedStart = orchestration.FbmSync.stateStart('', 'checking_session', 0, { preserveConflicts: true });
  check(so, 'phien moi bo conflict mo coi khi dong Activity khoi Sheet', [cleanedStart.metadata.conflicts.length, cleanedStart.counts.conflict, cleanedStart.locks['activity:ACT-DELETED']], [0, 0, undefined]);
  const restartFromConflict = orchestration.FbmSync.stateRead();
  restartFromConflict.phase = 'conflict';
  restartFromConflict.metadata.conflicts = [{ entity: 'activity', id: 'ACT-DELETED-2' }];
  restartFromConflict.counts.conflict = 1;
  restartFromConflict.locks = { 'activity:ACT-DELETED-2': { owner: 'sync', reason: 'conflict' } };
  orchestration.FbmSync.stateWrite(restartFromConflict);
  const restartedConflict = orchestration.FbmSync.start({ mode: 'read' });
  check(so, 'bam Dong bo ngay khi phase conflict phai tao phien moi', [restartedConflict.ok, restartedConflict.request.meta.kind, restartedConflict.status.metadata.conflicts.length, restartedConflict.status.counts.conflict], [true, 'authorize', 0, 0]);
  orchestration.FbmSync.readLocal = () => { throw new Error('sheet temporarily unavailable'); };
  const uncertainConflictState = orchestration.FbmSync.stateRead();
  uncertainConflictState.phase = 'conflict';
  uncertainConflictState.metadata.conflicts = [{ entity: 'activity', id: 'ACT-KEEP-ON-ERROR' }];
  uncertainConflictState.counts.conflict = 1;
  uncertainConflictState.locks = { 'activity:ACT-KEEP-ON-ERROR': { owner: 'sync', reason: 'conflict' } };
  orchestration.FbmSync.stateWrite(uncertainConflictState);
  const retainedOnReadError = orchestration.FbmSync.stateStart('', 'checking_session', 0, { preserveConflicts: true });
  check(so, 'loi doc Sheet thi giu conflict de an toan', [retainedOnReadError.metadata.conflicts.length, retainedOnReadError.counts.conflict, retainedOnReadError.locks['activity:ACT-KEEP-ON-ERROR'].reason], [1, 1, 'conflict']);
  orchestration.FbmSync.stateWrite(orchestration.FbmSync.stateStart('', 'idle', 0));
  const bulkStarted = orchestration.FbmSync.start({ mode: 'read', scan: 'activity_bulk' });
  check(so, 'start bulk Activity dung cursor authorize rieng', [bulkStarted.request.meta.kind, orchestration.FbmSync.stateRead().scan], ['authorize', 'activity_bulk']);
  check(so, 'bootstrap dung viewPage false', started.request.body.viewPage, false);
  check(so, 'bootstrap khong gui authorized cu', started.request.body.authorized, null);
  check(so, 'envelope mang runId/requestId va GAS luu moc response', [Boolean(started.request.meta.trace.runId), Boolean(started.request.meta.trace.requestId), orchestration.FbmSync.stateRead().activeRequestId === bulkStarted.request.meta.trace.requestId, orchestration.FbmSync.traceRead(5).some((item) => item.stage === 'response_built')], [true, true, true, true]);
  const dateEnvelope = orchestration.FbmSync.nextEnvelope({ url: 'https://fbo.com.vn:8888/AppService/FastBusiness.ReportExtenderService.asmx/GetGridViewPage', body: { gridPageValue: [new Date('2026-09-09T00:00:00Z'), { nested: new Date('2026-09-10T00:00:00Z') }] }, meta: { kind: 'grid' } });
  check(so, 'envelope khong tra Date o cursor phan trang Activity', [dateEnvelope.body.gridPageValue[0], dateEnvelope.body.gridPageValue[1].nested], ['/Date(1788912000000)/', '/Date(1788998400000)/']);
  check(so, 'response co trace bridge client van nhan dung reservation GAS', orchestration.FbmSync.responseRequestId({ transport: { trace: [{ requestId: 'gas-request-1' }, { stage: 'bridge_response_sent', clientRequestId: 'sidebar-waiter-1' }] } }), 'gas-request-1');
  let blockedEndpoint = '';
  try { orchestration.FbmSync.nextEnvelope({ url: 'https://fbo.com.vn:8888/Main/undefined', body: {}, meta: { kind: 'legacy' } }); } catch (err) { blockedEndpoint = String(err && err.message || err); }
  check(so, 'endpoint legacy undefined bi chan truoc khi cap envelope', blockedEndpoint.indexOf('FBM_ENDPOINT_MISSING') >= 0, true);
  check(so, 'GAS tao body wire escaped cho FBM', [dateEnvelope.bodyText.indexOf('\\/Date(1788912000000)\\/') >= 0, dateEnvelope.bodyText.indexOf('/Date(1788912000000)/') >= 0], [true, false]);
  const traceEvents = [{ stage: 'client_gas_call_started', requestId: 'trace-1', at: 1 }, { stage: 'client_gas_success', requestId: 'trace-1', at: 2 }];
  const writesBeforeTraceImport = propertyWrites;
  check(so, 'trace client ghi theo lo mot lan', [orchestration.FbmSync.traceImport(traceEvents), propertyWrites - writesBeforeTraceImport], [2, 1]);
  check(so, 'trace client gui lai khong ghi lap', [orchestration.FbmSync.traceImport(traceEvents), propertyWrites - writesBeforeTraceImport], [0, 1]);
  const retrySlice = orchestration.FbmSync.continue({ ok: false, status: 503, body: '', transport: { trace: [{ requestId: dateEnvelope.id }] } });
  check(so, 'loi doc tam thoi duoc retry co gioi han', [retrySlice.ok, retrySlice.retrying, retrySlice.request.meta.kind, orchestration.FbmSync.stateRead().retryCount], [true, true, 'authorize', 1]);
  const missingRequestId = orchestration.FbmSync.continue({ ok: true, status: 200, body: '{"d":{}}' });
  check(so, 'response thieu requestId bi chan khong an nham reservation', [missingRequestId.ok, missingRequestId.code, orchestration.FbmSync.stateRead().activeRequestId === retrySlice.request.id], [false, 'STALE_RESPONSE', true]);
  const blockedDuplicate = orchestration.FbmSync.start({ mode: 'read' });
  check(so, 'start khong cap request chong khi reservation cu con hieu luc', [blockedDuplicate.ok, blockedDuplicate.code, blockedDuplicate.request], [false, 'REQUEST_IN_FLIGHT', null]);
  orchestration.FbmSync.statePatch({ activeRequestId: '', deadlineAt: 0 });
  const resumed = orchestration.FbmSync.start({ mode: 'read' });
  check(so, 'start chi tiep tuc cursor sau khi reservation cu da thu hoi', [resumed.ok, resumed.resumed, resumed.request.meta.entity], [true, true, 'customer']);
  const staleState = JSON.parse(props.data[orchestration.FbmSync.STATE_KEY]);
  staleState.runId = 'old-run'; staleState.updatedAt = Date.now() - orchestration.FbmSync.STALE_RUN_MS - 1; staleState.lastProgressAt = staleState.updatedAt; staleState.activeRequestId = '';
  props.data[orchestration.FbmSync.STATE_KEY] = JSON.stringify(staleState);
  const restarted = orchestration.FbmSync.start({ mode: 'read' });
  check(so, 'authorize cu qua thoi gian stale duoc thay bang phien moi', [restarted.ok, restarted.resumed, orchestration.FbmSync.stateRead().runId === 'old-run'], [true, undefined, false]);
  const abandoned = orchestration.FbmSync.stateRead();
  abandoned.runId = 'abandoned-run'; abandoned.phase = 'pull_customer'; abandoned.updatedAt = Date.now() - orchestration.FbmSync.STALE_RUN_MS - 1;
  props.data[orchestration.FbmSync.STATE_KEY] = JSON.stringify(abandoned);
  const staleView = orchestration.FbmSync.statusView();
  check(so, 'status chi doc khong tu ghi de phien stale', [staleView.phase, staleView.lastFailureCode, orchestration.FbmSync.stateRead().runId], ['pull_customer', '', 'abandoned-run']);
  const uncertainWrite = orchestration.FbmSync.stateStart('customer', 'push', 1);
  uncertainWrite.cursor = { kind: 'push_wait' }; uncertainWrite.locks = { 'customer:C-1': { owner: 'sync' } };
  orchestration.FbmSync.stateWrite(uncertainWrite);
  const recoveredWrite = orchestration.FbmSync.recoverStaleRun(orchestration.FbmSync.stateRead(), Date.now() + orchestration.FbmSync.STALE_RUN_MS + 1);
  check(so, 'state ghi bi bo roi khong tu retry va giu khoa', [recoveredWrite.state.phase, recoveredWrite.state.lastFailureCode, !!recoveredWrite.state.locks['customer:C-1']], ['error', 'SYNC_STALE_WRITE', true]);
  check(so, 'lookup san pham dung controller FBM that', orchestration.FbmSync.SYNC_LOOKUPS.filter((item) => item.key === '@CAT_SAN_PHAM')[0].controller, 'crdmsp');
  const previewState = { metadata: {} };
  orchestration.FbmSync.previewRecords(previewState, 'customer', [{ fbmCustomerCode: 'ALT00010', companyName: 'Test', fbmId: 'A1' }]);
  check(so, 'preview luu ma va ten Customer doc tu FBM', previewState.metadata.preview.customers[0].code, 'ALT00010');
  const pullStatus = orchestration.FbmSync.stateRead();
  pullStatus.phase = 'pull_customer'; pullStatus.entity = 'customer'; pullStatus.mode = 'read'; orchestration.FbmSync.stateWrite(pullStatus);
  const pullView = orchestration.FbmSync.statusView();
  check(so, 'status noi ro chieu FBM ve ShinCRM', pullView.direction, 'FBM → ShinCRM');
  check(so, 'status noi ro dang dong bo khach hang', pullView.entityLabel, 'Khách hàng');
  const resumeState = orchestration.FbmSync.stateRead();
  resumeState.runId = 'resume-run'; resumeState.phase = 'pull_customer'; resumeState.cursor = { kind: 'customer_grid', type: 1, pageIndex: 2, pageValue: ['d', 't', 'x'], count: 2000 };
  orchestration.FbmSync.stateWrite(resumeState);
  const resumedGrid = orchestration.FbmSync.start({ mode: 'read' });
  check(so, 'Sidebar mo lai tiep tuc cursor doc Customer dang do', [resumedGrid.ok, resumedGrid.resumed, resumedGrid.request.meta.kind, resumedGrid.request.body.type], [true, true, 'grid', 1]);
  const pushStatus = orchestration.FbmSync.stateRead();
  pushStatus.phase = 'push'; pushStatus.entity = 'activity'; pushStatus.mode = 'write'; orchestration.FbmSync.stateWrite(pushStatus);
  const pushView = orchestration.FbmSync.statusView();
  check(so, 'status noi ro chieu ShinCRM sang FBM', pushView.direction, 'ShinCRM → FBM');
  check(so, 'status noi ro dang dong bo giao dich', pushView.entityLabel, 'Giao dịch');
  const compactState = orchestration.FbmSync.stateRead();
  compactState.cursor = { kind: 'push_wait', operation: 'activity_edit_save', entity: 'activity', index: 0, candidate: { record: { payload: new Array(200).join('khong_duoc_gui_') } }, oldValues: { details: new Array(200).join('old_value_') } };
  compactState.metadata.categoryGate = { map: { huge: new Array(500).join('category_') }, valid: { huge: true } };
  compactState.metadata.identityProbe = { spreadsheetId: 'sheet-probe', userId: '2037', accountName: 'ANHLT' };
  orchestration.FbmSync.stateWrite(compactState);
  const compactView = orchestration.FbmSync.statusView();
  check(so, 'status Sidebar khong tra Category gate va OldValue noi bo', [compactView.metadata.categoryGate, compactView.cursor.candidate, compactView.cursor.operation], [undefined, undefined, 'activity_edit_save']);
  check(so, 'status Sidebar giu identity probe de tu dien tai khoan', compactView.metadata.identityProbe, { spreadsheetId: 'sheet-probe', userId: '2037', accountName: 'ANHLT' });
  check(so, 'status Sidebar giu response nho khi state noi bo lon', JSON.stringify(compactView).length < 5000, true);

  const pausedState = orchestration.FbmSync.stateRead();
  pausedState.runId = 'paused-run'; pausedState.phase = 'paused'; pausedState.cursor = {};
  orchestration.FbmSync.stateWrite(pausedState);
  const restartedPaused = orchestration.FbmSync.start({ mode: 'read' });
  check(so, 'dong bo lai tu trang thai tam dung tao request FBM moi', [restartedPaused.ok, restartedPaused.request.meta.kind, restartedPaused.resumed], [true, 'authorize', undefined]);
  orchestration.FbmSync.statePatch({ runId: 'scheduled-run', phase: 'pull_customer', scheduledScan: 'customer', activeRequestId: '', deadlineAt: 0 });
  orchestration.fbmSyncCancel();
  check(so, 'dung dong bo xoa marker scheduler de khong tu chay lai', [orchestration.FbmSync.stateRead().phase, orchestration.FbmSync.stateRead().scheduledScan], ['idle', '']);

  const guards = taoHopCat({ FbmSync: {}, PropertiesService: { getScriptProperties: () => ({ getProperty: () => '' }), getDocumentProperties: () => ({ getProperty: () => null, setProperty: () => {} }) } });
  napServer(guards, 'fbm_sync/schema/FbmFields.js', 'fbm_sync/protocol/Protocol.js', 'fbm_sync/transport/TransportCore.js', 'fbm_sync/transport/PushFlow.js');
  check(so, 'push config chan account rong', guards.FbmSync.pushConfigErrors({ entity: 'customer', kind: 'edit' }, { accountName: '' }), 'Thiếu FBM_ACCOUNT_NAME; chiều đẩy đã bị dừng.');
  check(so, 'push config chan prefix va do dai khi tao customer', guards.FbmSync.pushConfigErrors({ entity: 'customer', kind: 'create' }, { accountName: 'Lê Tuấn Anh', customerPrefix: '', customerCodeLength: 8 }), 'Thiếu FBM_MA_KH_PREFIX hoặc FBM_MA_KH_LENGTH; không tạo khách mới.');
  check(so, 'push config cho activity sua khi account co', guards.FbmSync.pushConfigErrors({ entity: 'activity', kind: 'edit' }, { accountName: 'Lê Tuấn Anh' }), '');
  check(so, 'ma customer tu sinh hop le', guards.FbmSync.validateAutoCustomerCode('ALT00010', { customerPrefix: 'ALT', customerCodeLength: 8 }).ok, true);
  check(so, 'ma customer tu sinh sai tien to', guards.FbmSync.validateAutoCustomerCode('KH000010', { customerPrefix: 'ALT', customerCodeLength: 8 }).ok, false);
  check(so, 'ma customer tu sinh sai do dai', guards.FbmSync.validateAutoCustomerCode('ALT10', { customerPrefix: 'ALT', customerCodeLength: 8 }).ok, false);

  const lockState = { locks: { 'customer:C-1': { owner: 'sync' }, 'customer:C-2': { owner: 'user' } } };
  guards.FbmSync.unlockRecord = () => ({ locks: { 'customer:C-2': { owner: 'user' }, 'activity:A-1': { owner: 'sync' } } });
  guards.FbmSync.releasePushLock(lockState, 'customer', 'C-1');
  check(so, 'nha khoa push giu khoa khac', Object.keys(lockState.locks).sort().join(','), 'activity:A-1,customer:C-2');

  const recordLocks = taoHopCat({ FbmSync: {}, PropertiesService: { getDocumentProperties: () => {
    const data = recordLocks._props || (recordLocks._props = {});
    return { getProperty: (key) => data[key] || null, setProperty: (key, value) => { data[key] = String(value); } };
  } } });
  napServer(recordLocks, 'fbm_sync/state/State.js', 'fbm_sync/state/RecordLocks.js');
  recordLocks.FbmSync.stateStart('', 'idle', 0);
  recordLocks.FbmSync.lockRecord('customer', 'C-1', 'h1', 'sync');
  check(so, 'save bi chan khi record dang bi sync khoa', recordLocks.FbmSync.saveAllowed('customer', 'C-1', 'h1').code, 'RECORD_BUSY');
  check(so, 'edit begin bi chan khi record dang bi sync khoa', recordLocks.FbmSync.editBegin('customer', 'C-1', 'h1').code, 'RECORD_BUSY');
  recordLocks.FbmSync.unlockRecord('customer', 'C-1');
  check(so, 'save duoc phep sau khi nha khoa sync', recordLocks.FbmSync.saveAllowed('customer', 'C-1', 'h1').ok, true);
  recordLocks.FbmSync.lockRecord('customer', 'C-2', 'h2', 'user');
  recordLocks.FbmSync.stateStart('', 'checking_session', 0);
  check(so, 'phien sync moi giu khoa cua form nguoi dung', recordLocks.FbmSync.stateRead().locks['customer:C-2'].owner, 'user');

  const schedulerData = {};
  const schedulerPropertyApi = { getProperty: (key) => schedulerData[key] || null, setProperty: (key, value) => { schedulerData[key] = String(value); } };
  const scheduler = taoHopCat({ FbmSync: {}, SETTINGS: { LOCK_WAIT_MS: 1 }, PropertiesService: { getDocumentProperties: () => schedulerPropertyApi }, LockService: { getDocumentLock: () => ({ tryLock: () => true, releaseLock: () => {} }) } });
  napServer(scheduler, 'fbm_sync/schema/FbmFields.js', 'fbm_sync/state/State.js', 'fbm_sync/transport/TransportCore.js', 'fbm_sync/report/Report.js', 'fbm_sync/state/Scheduler.js');
  const schedule = scheduler.FbmSync.schedule();
  check(so, 'scheduler Activity dung chu ky 30 phut', [schedule.activityMinutes, Number(schedulerData.FBM_SYNC_NEXT_ACTIVITY_SCAN) - Date.now() <= 30 * 60 * 1000], [30, true]);
  schedulerData.FBM_SYNC_NEXT_CUSTOMER_SCAN = '1000';
  const claimed = scheduler.FbmSync.schedulerClaim('customer', 1000);
  check(so, 'scheduler claim mot ky Customer va doi marker', [claimed.ok, claimed.kind, scheduler.FbmSync.stateRead().scheduledScan, Number(schedulerData.FBM_SYNC_NEXT_CUSTOMER_SCAN) > 1000], [true, 'customer', 'customer', true]);
  const notDue = scheduler.FbmSync.schedulerClaim('customer', 1001);
  check(so, 'scheduler khong tao ky Customer thu hai khi marker chua den', [notDue.ok, notDue.code], [false, 'NOT_DUE']);
  const active = scheduler.FbmSync.stateRead();
  active.phase = 'pull_customer'; active.runId = 'busy'; scheduler.FbmSync.stateWrite(active);
  schedulerData.FBM_SYNC_NEXT_ACTIVITY_SCAN = '1000';
  const busy = scheduler.FbmSync.schedulerClaim('activity', 1000);
  check(so, 'scheduler bo qua khi dang co phien', [busy.ok, busy.code], [false, 'SYNC_ALREADY_RUNNING']);
  active.updatedAt = Date.now() - scheduler.FbmSync.STALE_RUN_MS - 1;
  schedulerData[scheduler.FbmSync.STATE_KEY] = JSON.stringify(active);
  schedulerData.FBM_SYNC_NEXT_ACTIVITY_SCAN = String(Date.now() - 1);
  const staleClaim = scheduler.FbmSync.schedulerClaim('activity', Date.now());
  check(so, 'scheduler thu hoi phien cu va nhan ky moi', [staleClaim.ok, staleClaim.kind, scheduler.FbmSync.stateRead().lastFailureCode], [true, 'activity', 'SYNC_STALE_RUN']);
  const supervised = scheduler.FbmSync.stateStart('activity', 'push', 1);
  supervised.cursor = { kind: 'push_wait', operation: 'activity_edit_save' }; supervised.current = 'ACT-1'; supervised.lastProgressAt = Date.now() - scheduler.FbmSync.STALE_RUN_MS - 1;
  scheduler.FbmSync.stateWrite(supervised);
  const supervisorResult = scheduler.FbmSync.supervise(Date.now());
  check(so, 'Supervisor danh dau phien ghi treo va khong tu retry', [supervisorResult.stale, scheduler.FbmSync.stateRead().phase, scheduler.FbmSync.stateRead().lastFailureCode], [true, 'error', 'SUPERVISOR_TIMEOUT_AT_PUSH']);
  schedulerData.FBM_SYNC_NEXT_HEARTBEAT = '0';
  const errorClaim = scheduler.FbmSync.schedulerClaim('heartbeat', Date.now());
  check(so, 'Scheduler khong ghi de loi phien push da treo', [errorClaim.ok, errorClaim.code, scheduler.FbmSync.stateRead().phase, scheduler.FbmSync.stateRead().lastFailureCode], [false, 'SYNC_ERROR_REQUIRES_MANUAL_RESTART', 'error', 'SUPERVISOR_TIMEOUT_AT_PUSH']);

  const heartbeatData = {};
  const heartbeatPropertyApi = { getProperty: (key) => heartbeatData[key] || null, setProperty: (key, value) => { heartbeatData[key] = String(value); } };
  const heartbeat = taoHopCat({ FbmSync: {}, PropertiesService: { getDocumentProperties: () => heartbeatPropertyApi, getScriptProperties: () => heartbeatPropertyApi }, LockService: { getDocumentLock: () => ({ tryLock: () => true, releaseLock: () => {} }) } });
  napServer(heartbeat, 'fbm_sync/schema/FbmFields.js', 'fbm_sync/protocol/Protocol.js', 'fbm_sync/state/State.js', 'fbm_sync/diagnostic/Trace.js', 'fbm_sync/state/Scheduler.js', 'fbm_sync/report/Report.js', 'fbm_sync/read/GridRead.js', 'fbm_sync/write/RequestBuilders.js', 'fbm_sync/transport/TransportCore.js', 'fbm_sync/transport/PullFlow.js', 'fbm_sync/transport/EntryPoints.js');
  const heartbeatStateRead = heartbeat.FbmSync.stateRead;
  heartbeat.FbmSync.stateRead = () => ({ session: { expired: true } });
  const relayProbe = heartbeat.fbmSyncRelayProbe();
  check(so, 'relay probe tra co trang thai cong tac va phien', [relayProbe.ok, relayProbe.code, relayProbe.sessionExpired], [true, 'RELAY_PROBE_OK', true]);
  heartbeat.FbmSync.stateRead = heartbeatStateRead;
  heartbeat.FbmSync.stateStart('', 'idle', 0);
  heartbeat.FbmSync.statePatch({ session: { cookie: '', expired: false } });
  const heartbeatRequest = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  check(so, 'GAS cap heartbeat de capture generic khi chua biet cookie', [heartbeatRequest.ok, heartbeatRequest.code, heartbeatRequest.request.meta.kind, heartbeatRequest.request.body.type, heartbeatRequest.request.body.count, heartbeatRequest.request.body.sortExpression, heartbeatRequest.request.bodyText.indexOf('{{FBM_PAYLOAD_COOKIE}}') >= 0], [true, 'HEARTBEAT_REQUEST_READY', 'heartbeat', 0, 1, null, true]);
  const overlappingHeartbeat = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  check(so, 'heartbeat không cấp request chồng khi reservation còn hiệu lực', [overlappingHeartbeat.ok, overlappingHeartbeat.code, overlappingHeartbeat.request], [false, 'REQUEST_IN_FLIGHT', null]);
  const transportFailure = heartbeat.FbmSync.heartbeatTransportFailure({ requestId: heartbeatRequest.request.id, code: 'FBM_TAB_NOT_FOUND', message: 'Không tìm thấy tab FBM đang mở.' });
  check(so, 'GAS thu hồi reservation khi Extension không có tab FBM', [transportFailure.ok, transportFailure.code, heartbeat.FbmSync.stateRead().activeRequestId], [false, 'FBM_TAB_NOT_FOUND', '']);
  const staleTransportFailure = heartbeat.FbmSync.heartbeatTransportFailure({ requestId: heartbeatRequest.request.id, code: 'FBM_TAB_NOT_FOUND' });
  check(so, 'transport failure cũ không đụng reservation mới', [staleTransportFailure.ok, staleTransportFailure.code], [false, 'STALE_RESPONSE']);
  const firstHeartbeatRequest = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  const firstHeartbeat = heartbeat.fbmSyncHeartbeat({ d: { TotalRowCount: 2 }, transport: { trace: [{ requestId: firstHeartbeatRequest.request.id }] } });
  check(so, 'heartbeat luu lan song va tong Customer dau tien', [heartbeat.FbmSync.stateRead().session.lastHeartbeatAt > 0, heartbeat.FbmSync.stateRead().session.customerTotal, firstHeartbeat.request], [true, 2, null]);
  heartbeat.FbmSync.statePatch({ session: { expired: true } });
   const blockedHeartbeatRequest = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
   check(so, 'GAS giu state cho dang nhap khi session het han', heartbeat.FbmSync.stateRead().phase, 'paused');
   check(so, 'GAS giu trang thai cho dang nhap va khong cap request FBM', [blockedHeartbeatRequest.ok, blockedHeartbeatRequest.code, blockedHeartbeatRequest.request], [true, 'AUTO_LOGIN_NOT_CONFIGURED', null]);
  heartbeat.FbmSync.statePatch({ runId: '', phase: 'idle', cursor: {}, activeRequestId: '', session: { cookie: '', expired: false, lastHeartbeatAt: 0 } });
  const missingCookieRequest = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  check(so, 'cookie chua capture khong bi coi la logout', [missingCookieRequest.ok, missingCookieRequest.code, missingCookieRequest.request.meta.kind], [true, 'HEARTBEAT_REQUEST_READY', 'heartbeat']);
  heartbeat.FbmSync.statePatch({ session: { customerTotal: 2, cookie: 'userFHN_CRM_App', expired: false }, scheduledScan: 'customer', phase: 'idle', runId: '', cursor: {}, activeRequestId: '', deadlineAt: 0 });
  const scheduledRequest = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  check(so, 'heartbeat scheduled phai co reservation truoc khi nhan response', [scheduledRequest.ok, scheduledRequest.request.meta.kind], [true, 'heartbeat']);
  const scheduledHeartbeat = heartbeat.fbmSyncHeartbeat({ d: { TotalRowCount: 2 }, transport: { trace: [{ requestId: scheduledRequest.request.id }] } });
  check(so, 'heartbeat handoff bat dau full Customer khi scheduler den han', [scheduledHeartbeat.ok, scheduledHeartbeat.request.meta.kind, scheduledHeartbeat.status.phase], [true, 'authorize', 'checking_session']);
  const continuedBackground = heartbeat.fbmSyncHeartbeat({ d: { Authorized: 'auth-customer' }, transport: { trace: [{ requestId: scheduledHeartbeat.request.id }], payloadCookie: 'userFHN_CRM_App' } });
  check(so, 'response authorize cua phien nen di qua continuation chung', [continuedBackground.ok, continuedBackground.request.meta.kind, continuedBackground.request.meta.entity, heartbeat.FbmSync.stateRead().cursor.kind], [true, 'authorize', 'activity', 'authorize_activity']);
  heartbeat.FbmSync.statePatch({ runId: 'slice-run', origin: 'background', phase: 'pull_customer', cursor: { kind: 'customer_grid', type: 1, pageIndex: 3, pageValue: ['d', 't', 'x'], count: 2000 }, activeRequestId: '', deadlineAt: 0 });
  const resumedAfterSlice = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  check(so, 'alarm ke tiep tiep tuc cursor sau khi het relay slice', [resumedAfterSlice.ok, resumedAfterSlice.code, resumedAfterSlice.resumed, resumedAfterSlice.request.meta.kind, resumedAfterSlice.request.body.gridPageIndex], [true, 'SYNC_RESUME_REQUEST_READY', true, 'grid', 3]);
  heartbeat.FbmSync.statePatch({ runId: 'slice-limit-run', phase: 'pull_customer', cursor: { kind: 'customer_grid', type: 1, pageIndex: 4, pageValue: ['e', 't', 'x'], count: 2000 }, activeRequestId: 'slice-request', deadlineAt: Date.now() + 60000 });
  const capped = heartbeat.FbmSync.limitRelayResult({ ok: true, request: { id: 'next-request' }, status: heartbeat.FbmSync.statusView() }, heartbeat.FbmSync.RELAY_HOP_LIMIT);
  check(so, 'dat gioi han hop thu hoi reservation nhung giu cursor de alarm sau tiep tuc', [capped.code, capped.request, heartbeat.FbmSync.stateRead().activeRequestId, heartbeat.FbmSync.stateRead().cursor.pageIndex], ['RELAY_SLICE_COMPLETE', null, '', 4]);
  const activeState = heartbeat.FbmSync.stateRead();
  activeState.phase = 'pull_customer'; activeState.runId = 'heartbeat-run'; activeState.cursor = { kind: 'customer_grid', type: 0, pageIndex: -1, pageValue: null, count: 2000 }; activeState.activeRequestId = 'in-flight-request';
  heartbeat.FbmSync.stateWrite(activeState);
  const overlapDuringSync = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  check(so, 'heartbeat khong ghi de cursor phien Customer dang chay', [overlapDuringSync.ok, overlapDuringSync.code, overlapDuringSync.request], [false, 'REQUEST_IN_FLIGHT', null]);
  heartbeat.FbmSync.statePatch({ runId: '', phase: 'idle', cursor: {}, activeRequestId: '', deadlineAt: 0, session: { customerTotal: 2, cookie: 'userFHN_CRM_App', expired: false }, scheduledScan: '' });
  const changedRequest = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  check(so, 'heartbeat thay doi tong Customer co reservation moi', [changedRequest.ok, changedRequest.request.meta.kind], [true, 'heartbeat']);
  const changedHeartbeat = heartbeat.fbmSyncHeartbeat({ d: { TotalRowCount: 3 }, transport: { trace: [{ requestId: changedRequest.request.id }] } });
  check(so, 'heartbeat tong Customer thay doi kich full Customer', [changedHeartbeat.request.meta.kind, changedHeartbeat.status.phase], ['authorize', 'checking_session']);
  heartbeat.FbmSync.statePatch({ runId: '', phase: 'idle', cursor: {}, activeRequestId: '', deadlineAt: 0, session: { cookie: 'userFHN_CRM_App', expired: false }, scheduledScan: '' });
  const failedRequest = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  const failedHeartbeat = heartbeat.fbmSyncHeartbeat({ ok: false, status: 500, body: '{"Message":"There was an error processing the request."}', transport: { trace: [{ requestId: failedRequest.request.id }] } });
  check(so, 'heartbeat HTTP 500 dung phien va tra loi ro rang', [failedHeartbeat.ok, failedHeartbeat.code, heartbeat.FbmSync.stateRead().lastFailureCode], [false, 'FBM_BUSINESS_ERROR', 'FBM_BUSINESS_ERROR']);
  heartbeat.FbmSync.statePatch({ runId: '', phase: 'idle', cursor: {}, activeRequestId: '', deadlineAt: 0, session: { cookie: 'userFHN_CRM_App', expired: false } });
  const emptyRequest = heartbeat.fbmSyncHeartbeatRequest({ source: 'alarm' });
  check(so, 'heartbeat shape rong co reservation truoc khi phan loai', [emptyRequest.ok, emptyRequest.request.meta.kind], [true, 'heartbeat']);
  const emptyHeartbeat = heartbeat.fbmSyncHeartbeat({ ok: true, status: 200, body: '{"d":{}}', transport: { trace: [{ requestId: emptyRequest.request.id }] } });
  check(so, 'heartbeat khong co shape Customer dung phai fail-closed nhu het phien', [emptyHeartbeat.ok, emptyHeartbeat.code, heartbeat.FbmSync.stateRead().session.expired], [false, 'SESSION_EXPIRED', true]);
  const backgroundState = heartbeat.FbmSync.stateRead();
  backgroundState.runId = 'background-run'; backgroundState.origin = 'background'; backgroundState.phase = 'pull_customer'; backgroundState.entity = 'customer'; backgroundState.activeRequestId = 'background-request'; backgroundState.cursor = { kind: 'customer_grid', type: 0, pageIndex: 0, pageValue: null, count: 2000 }; backgroundState.metadata.manualPending = null;
  heartbeat.FbmSync.stateWrite(backgroundState);
  const manualRequest = heartbeat.FbmSync.start({ mode: 'read', manual: true });
  check(so, 'manual yeu cau dung phien nen sau response hien tai', [manualRequest.ok, manualRequest.code, heartbeat.FbmSync.stateRead().metadata.manualPending.mode], [false, 'SYNC_BACKGROUND_STOPPING', 'read']);
  const stoppedBackground = heartbeat.FbmSync.continue({ d: { Rows: [] }, transport: { trace: [{ requestId: 'background-request' }] } });
  check(so, 'phien nen dung va san sang cho manual sau khi nhan response', [stoppedBackground.manualReady, heartbeat.FbmSync.stateRead().phase, heartbeat.FbmSync.stateRead().runId], [true, 'idle', '']);
  const preservedState = heartbeat.FbmSync.stateRead();
  preservedState.runId = 'preserve-run'; preservedState.phase = 'pull_customer'; preservedState.cursor = { kind: 'customer_grid', pageIndex: 4 }; preservedState.activeRequestId = 'preserve-request';
  heartbeat.FbmSync.stateWrite(preservedState);
  heartbeat.FbmSync.setMasterEnabled(false);
  const blockedByMaster = heartbeat.FbmSync.nextEnvelope({ url: 'https://fbo.com.vn:8888/Main/blocked', body: {}, meta: { kind: 'grid' } });
  const keptAfterMasterOff = heartbeat.FbmSync.stateRead();
  check(so, 'tắt công tắc tổng giữ cursor va reservation đang bay', [blockedByMaster, keptAfterMasterOff.cursor.kind, keptAfterMasterOff.activeRequestId, keptAfterMasterOff.phase], [null, 'customer_grid', 'preserve-request', 'paused']);
  heartbeat.FbmSync.setMasterEnabled(true);
  const cancelledState = heartbeat.FbmSync.stateRead();
  cancelledState.runId = 'cancel-run'; cancelledState.phase = 'checking_session'; cancelledState.cursor = { kind: 'authorize_customer' }; cancelledState.activeRequestId = 'cancel-request';
  heartbeat.FbmSync.stateWrite(cancelledState);
  const pendingCancel = heartbeat.fbmSyncCancel();
  check(so, 'dung phien khi request dang bay giu reservation', [pendingCancel.code, heartbeat.FbmSync.stateRead().activeRequestId, heartbeat.FbmSync.stateRead().metadata.cancelPending], ['SYNC_CANCEL_PENDING', 'cancel-request', true]);
  const stoppedAfterResponse = heartbeat.FbmSync.continue({ d: { Authorized: 'auth-customer' }, transport: { trace: [{ requestId: 'cancel-request' }] } });
  check(so, 'response hien tai duoc dong nhung khong cap request tiep', [stoppedAfterResponse.ok, stoppedAfterResponse.request, heartbeat.FbmSync.stateRead().phase, heartbeat.FbmSync.stateRead().activeRequestId], [true, null, 'paused', '']);
}

module.exports = { chay };
